name: Hello World Workflow

on:
  push:
    branches:
      - 2-bug-fix-2

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, World!"
